# Generated by Django 2.2.6 on 2019-10-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThePress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='언론사 이름')),
                ('main_url', models.URLField(unique=True, verbose_name='대표 홈페이지')),
                ('mobile_url', models.URLField(unique=True, verbose_name='모바일 홈페이지')),
            ],
        ),
        migrations.CreateModel(
            name='ReporterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.ThePress')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Reporter')),
            ],
        ),
    ]
