# Generated by Django 2.2.6 on 2019-10-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterdetail',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='reporterdetail',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='reporterdetail',
            name='reporter',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.Reporter'),
        ),
    ]
