# Generated by Django 2.2.6 on 2019-10-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('organization', '0002_auto_20191028_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Reporter')),
            ],
        ),
    ]
