# Generated by Django 2.2.6 on 2019-11-09 17:25

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_articlereporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressYonhap',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(organization.models.PressMixin, 'organization.thepress'),
        ),
        migrations.AddField(
            model_name='thepress',
            name='encoding',
            field=models.CharField(choices=[('UTF-8', 'UTF-8'), ('euc-kr', 'euc-kr')], default='UTF-8', max_length=8, verbose_name='페이지 인코딩'),
        ),
    ]
