# Generated by Django 2.2.6 on 2020-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20191109_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='thepress',
            name='user_agent',
            field=models.CharField(default='', max_length=128, verbose_name='UserAgent'),
            preserve_default=False,
        ),
    ]
