# Generated by Django 2.2.6 on 2019-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_articlereporter'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reporters',
            field=models.ManyToManyField(through='organization.ArticleReporter', to='organization.Reporter'),
        ),
    ]
