# Generated by Django 2.2.6 on 2019-10-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191028_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='com_result_content',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='com_result_content_rule_id', to='analysis.MatchRule'),
        ),
        migrations.AlterField(
            model_name='article',
            name='com_result_title',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='com_result_title_rule_id', to='analysis.MatchRule'),
        ),
    ]
