# Generated by Django 2.2.6 on 2019-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articlecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='기사 업데이트 시간'),
        ),
    ]
