# Generated by Django 2.2.6 on 2019-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191028_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='이메일 판단 근거'),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='제목'),
        ),
    ]
