# Generated by Django 2.2.6 on 2019-11-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191104_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='이름 판단 근거'),
        ),
    ]
